// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace AndroidRecorder
{
	public partial class PreferencesViewController : NSViewController
	{
		public PreferencesViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad() { 
        
        }

        partial void SaveSettingButton(NSObject sender)
        {
            Console.WriteLine("push save setting button");
        }

    }
}
